name: chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
   sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  geolocator: ^13.0.1
  # flutter_facebook_auth: ^6.2.0
  # twitter_login: ^4.4.2
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.1
  # google_maps_flutter: ^2.9.0
  device_preview: ^1.1.0
  flutter_timer_countdown: ^1.0.5
  cupertino_icons: ^1.0.8
  provider: ^6.1.2 
  http: ^1.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  icons_plus: ^4.0.0
  animated_text_kit: ^4.2.1
  flutter_animate: ^4.5.2
  table_calendar: ^3.1.2
  flutter_svg: ^2.0.17
  flutter_slidable: ^3.1.2
  google_maps_flutter: ^2.9.0
  audioplayers: ^6.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#00292A"
  image: assets/images/icon.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    color: "#00292A"
    image: assets/images/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-VariableFont_wght.ttf
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica compressed rg.ttf
    - family: Geo
      fonts:
        - asset: assets/fonts/Geo.otf
    - family: Arcane Nine
      fonts:
        - asset: assets/fonts/Arcane Nine.otf
    - family: Gasoek One
      fonts:
        - asset: assets/fonts/GasoekOne-Regular.ttf
